#pragma once

#define SKILL_TYPE_ATTACK 0
#define SKILL_TYPE_COUNTER 2
#define SKILL_TYPE_DEBUFF 4
#define SKILL_TYPE_HEAL 1
#define SKILL_TYPE_BUFF 3

#define DAMAGE_TYPE_MAGIC 2
#define DAMAGE_TYPE_FIRE 4
#define DAMAGE_TYPE_PIERCING 64
#define DAMAGE_TYPE_ICE 8
#define DAMAGE_TYPE_LIGHTNING 16
#define DAMAGE_TYPE_BLUDGEONING 128
#define DAMAGE_TYPE_SLASHING 32
#define DAMAGE_TYPE_PHYSICAL 1

