int autoImageMap[] = 
{
	RESOURCE_ID_IMAGE_RAT,
	RESOURCE_ID_IMAGE_DUNGEONSTRAIGHT,
	RESOURCE_ID_IMAGE_DUNGEONDEADEND,
	RESOURCE_ID_IMAGE_VILLAGE_EXTERIOR,
	RESOURCE_ID_IMAGE_VILLAGE_INTERIOR,
	RESOURCE_ID_IMAGE_ROAD1,
	RESOURCE_ID_IMAGE_ROAD2,
	RESOURCE_ID_IMAGE_ROAD3,
	RESOURCE_ID_IMAGE_NEWFLOOR,
	RESOURCE_ID_IMAGE_DUNGEONRIGHT,
	RESOURCE_ID_IMAGE_DUNGEONLEFT,
};
