#pragma once

#define SKILL_TARGET_ENEMY 0
#define SKILL_TARGET_SELF 1
#define SKILL_TARGET_COUNTER 2

#define DAMAGE_TYPE_MAGIC 2
#define DAMAGE_TYPE_HOLY 256
#define DAMAGE_TYPE_FIRE 4
#define DAMAGE_TYPE_PIERCING 64
#define DAMAGE_TYPE_ICE 8
#define DAMAGE_TYPE_LIGHTNING 16
#define DAMAGE_TYPE_BLUDGEONING 128
#define DAMAGE_TYPE_SLASHING 32
#define DAMAGE_TYPE_PHYSICAL 1

#define STATUS_EFFECT_SLOW 2
#define STATUS_EFFECT_STUN 0
#define STATUS_EFFECT_POISON 1
#define STATUS_EFFECT_HASTE 3
#define STATUS_EFFECT_PASSIFY 5
#define STATUS_EFFECT_SILENCE 4
#define STATUS_EFFECT_COUNT 6

#define SKILL_PROPERTIES_SLOW 4
#define SKILL_PROPERTIES_PASSIFY 32
#define SKILL_PROPERTIES_POISON 2
#define SKILL_PROPERTIES_HASTE 8
#define SKILL_PROPERTIES_STUN 1
#define SKILL_PROPERTIES_SILENCE 16

