#define MAX_MONSTERS 10
#define MAX_ADJACENT_LOCATIONS 10
#define MAX_SKILLS_IN_LIST 15
#define MAX_CLASSES 5
#define MAX_STORY_NAME_LENGTH 32
#define MAX_STORY_DESC_LENGTH 64
#define MAX_BACKGROUND_IMAGES 10
