#pragma once

#define COMBATANT_RANK_RANKS 6
#define COMBATANT_RANK_RANKC 3
#define COMBATANT_RANK_RANKB 4
#define COMBATANT_RANK_RANKA 5
#define COMBATANT_RANK_RANKF 0
#define COMBATANT_RANK_RANKE 1
#define COMBATANT_RANK_RANKD 2

